### ISSUE TITLE
Last chunk not copied if the chunksize is not a factor of the dimension 

### ISSUE THREAD

**Issue by russfiedler** [coecms/mppnccombine-fast#29] opened 2018-11-13 06:00 UTC
We've found in the 75 level Cosima model that the bottom 18 levels are not copied correctly. The decomposed files have a vertical chunksize of 19 which doesn't go. 3*19+18=75. Note that there were also some variables in the same file that were mapped to 80 levels in density space. These had a chunksize of 20 and look to be fine.

**Comment by aekiss** [comment] 2018-11-13 06:29
Dang. Thanks for spotting this @russfiedler. Everything below 2400m is missing in the final 5 runs of 01deg_jra55v13_iaf which used mppnccombine-fast. I'll re-do them.

**Comment by aidanheerdegen** [comment] 2018-11-25 22:41
Have you had a chance to look at this @ScottWales?

**Comment by ScottWales** [comment] 2018-11-25 23:50
I'm not able to reproduce by creating a vertically chunked test file, can you please point me to the location of this run's input files?

**Comment by aekiss** [comment] 2018-11-26 00:11
Try these: `/short/v45/aek156/access-om2/control/01deg_jra55_iaf/archive/output197/ocean/ocean.nc.*`

**Comment by aidanheerdegen** [comment] 2018-11-28 05:32
@aekiss Can you confirm that this collated version of those files has fixed this issue?

`/short/v45/aph502/collate_tenth/issue_29.nc`

**Comment by aekiss** [comment] 2018-11-28 07:02
I expect it didn't work, as the file size is 2Gb too small (35Gb instead of 37). Presumably there are no differences in compression that could account for that?

I tried to check it with the xarray `identical` method but hit a memory error on the VDI: https://github.com/aekiss/notebooks/blob/master/check-mppnccombine.ipynb

I guess it would need to be run as a job instead. I'll try that next.

**Comment by aekiss** [comment] 2018-11-28 22:16
`/short/v45/aek156/access-om2/control/01deg_jra55_iaf/archive/output197/ocean/ocean.nc` and `/short/v45/aph502/collate_tenth/issue_29.nc` differ (xarray `identical` returned false). I expect the difference is somewhere in the data since it seems to check metadata first but took almost 2 hours to find a difference. For the record it required >80Gb, <128Gb memory.

**Comment by aekiss** [comment] 2018-11-28 22:20
A quick, very incomplete check with ncview shows there is data below 2400m, so while this particular issue may have been resolved, it seems there are other bugs still lurking.

**Comment by aidanheerdegen** [comment] 2018-11-29 00:30
Same as https://github.com/coecms/mppnccombine-fast/issues/28

See https://gist.github.com/7061e21cd879cfa52db62be193e16c43

```ds_slow.diff_cbt_t[0,0,:,:].where(ds_fast.diff_cbt_t[0,0,:,:] != ds_slow.diff_cbt_t[0,0,:,:]).plot()```

![unknown-2](https://user-images.githubusercontent.com/6063709/49191301-29800800-f3ca-11e8-9c0e-2500cd097b8a.png)

**Comment by russfiedler** [comment] 2018-11-29 01:11
Output stops at the point (2160,2160). 2160 has both 180 and 135 as factors. These are the chunk sizes in the x and y direction. I suspect a switcheroo of the indices has happened somewhere.

**Comment by ScottWales** [comment] 2018-11-29 01:39
As with #28 I cannot reproduce with the beta branch - @aidanheerdegen what repository version are you using?

**Comment by aidanheerdegen** [comment] 2018-11-29 03:00
The `beta` branch. I guess it is also me stuffing up the collation somehow (as with https://github.com/coecms/mppnccombine-fast/issues/28). I'll check it all again.

**Comment by aidanheerdegen** [comment] 2018-12-05 04:57
I believe this is now fixed. The previous collation was wrong due to https://github.com/coecms/mppnccombine-fast/issues/34

```
ds_slow.diff_cbt_t[1,0,:,:].where(ds_fast.diff_cbt_t[1,0,:,:] != ds_slow.diff_cbt_t[1,0,:,:]).plot(size=10)
```
<img width="932" alt="screen shot 2018-12-05 at 1 56 02 pm" src="https://user-images.githubusercontent.com/6063709/49487221-8cbfdd80-f895-11e8-9c74-0110adc46015.png">

 I am trying some other verification pathways, but these are damn large files

**Comment by aidanheerdegen** [comment] 2018-12-06 04:51
Confirmed this is now fixed.

**Closed by aidanheerdegen** 2018-12-06 04:51 UTC
